### ISSUE TITLE
Add a paramter to skip version check for Get-Office365Endpoints.ps1

### ISSUE THREAD

**Issue by mikes-gh** [jhochwald/PowerShell-collection#4]
## Expected Behavior
Be able to list ips and urls regardless of the version we last checked

## Current Behavior
Cannot get ip or url list if already checked against current version

## Possible Solution
Add parameter to skip version check
Something like -SkipVersionCheck $true or -ForceOutput $true

## Steps to Reproduce

1. Run Get-Office365Endpoints.ps1
2. Run again outputs "Office 365 worldwide commercial service instance endpoints are up-to-date"

## Context
I have to keep deleteing the temp file or change the script to get a list of ips or urls

## Your Environment
Windows 7 sp1 plus latest updates
PS C:\Users\mikes\Desktop> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10514  6

**Comment by jhochwald** [comment]
Great idea!
Will implement a `-force` Parameter

**Comment by mikes-gh** [comment]
I know -Force is nice and short to type but I think something that describes the parameter better.
-VersionCheck $false (We do have auto complete in powershell)

Personally I also think the default could be $false and you would only have to use -VersionCheck $true in your automated scripts.

Thansk fot the script :smile:

**Comment by jhochwald** [comment]
I uploaded a version that contains your request :-)

**Comment by mikes-gh** [comment]
Thank you :smile:
