### ISSUE TITLE
Cant run Invoke-BackupBitlockerRecoveryKey.ps1

### ISSUE THREAD

**Issue by BladefoxTB** [jhochwald/PowerShell-collection#8]
WARNING: The names of some imported commands from the module 'BitLocker' include unapproved verbs that might make them
less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
C:\scripts\Powershell\Invoke-BackupBitlockerRecoveryKey.ps1 : Parameter set cannot be resolved using the specified
named parameters.
At line:1 char:1
+ .\Invoke-BackupBitlockerRecoveryKey.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [Write-Error], Exception
    + FullyQualifiedErrorId : System.Exception,Invoke-BackupBitlockerRecoveryKey.ps1

**Comment by BladefoxTB** [comment]
It seems to work on an already encrypted machine which is nice but I got the above error on a machine I wanted to activate bitlocker on and export to aad

**Comment by jhochwald** [comment]
This is something I can NOT fix, due to the fact, that the **BitLocker** is from Microsoft!

This is what can do, before execute my script:
```PowerShell
Import-Module -Name BitLocker -Force -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
```

Sorry!
